import Head from "next/head";
import Navbar from "./Navbar";

export default function Layout({ children, onClick }) {
  return (
    <div className="bg-grey w-100 h-96">
      <Head>
        <title>Up4Grabs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar onClick={onClick}/>
      <div>{children}</div>
    </div>
  );
}
