import Head from "next/head";
import Navbar from "./Navbar";
import Footer from "../components/Footer";

export default function Layout({ children, users }) {
  return (
    <div className="bg-grey h-full">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Teko:wght@700&display=swap"
          rel="stylesheet"
        />
        <title>Up4Grabs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.tiles.mapbox.com/mapbox-gl-js/v<YOUR_MAPBOX_VERSION>/mapbox-gl.css"
          rel="stylesheet"
        />
      </Head>
      <Navbar users={users}/>
      <div>{children}</div>
      <Footer />
    </div>
  );
}
