import Head from "next/head";
import Navbar from "../components/NavBar";
import Header from "../components/Header";

const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

export async function getStaticProps() {
  const users = await prisma.user.findMany();

  return {
    props: { users },
  };
}

export default function Home({ users }) {
  return (
    <div className="bg-grey w-100 h-96">
      <Head>
        <title>Up4Grabs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      {/* <h1 className="bg-grey text-9xl text-center">Up4Grabs</h1>
        <ul className="w-fit">
          {users.map((user) => (
            <li key={user.id} className="text-green">
              {user.name}
            </li>
          ))}
        </ul> */}
    </div>
  );
}
