import Head from "next/head";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import Listings from "../components/Listings";

const { PrismaClient } = require("@prisma/client");
export async function getStaticProps() {
  const prisma = new PrismaClient();

  const listings = await prisma.listings.findMany();
  console.log("inside fetcher", listings);
  return {
    props: { listings },
  };
}

export default function Home({listings}) {
  return (
    <div className="bg-grey w-100 h-96">
      <Head>
        <title>Up4Grabs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2 md:gap-4 lg:gap-6 p-5">
      <Listings listings={listings}/>
      </div>
    </div>
  );
}
