import Head from "next/head";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

export async function getStaticProps() {
  const users = await prisma.user.findMany();
  return {
    props: { users },
  };
}

export default function Home({ users }) {
  return (
    <div className="">
      <Head>
        <title>Create Next app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-blue">
        <ul>
          {users.map((user) => (
            <li key={user.id} className="text-green">
              {user.name}
            </li>
          ))}
        </ul>
      </main>

      <footer className=""></footer>
    </div>
  );
}
